spring.application.name=demo-mvc

#PORT
server.port=8080

# Configuração de porta para evitar conflito
#server.port=8081

# Para ver quem está ocupando a porta 8080, e finalizar o processo
# netstat -ano | findstr :8080
# taskkill /PID <PID_encontrado> /F


#MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/demo_mvc?createDatabaseIfNotExist=True&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true

#THYMELEAF
spring.thymeleaf.cache = false









