spring.application.name=demo-mvc

# Configuração de porta para evitar conflito
#server.port=8081

# Para ver quem está ocupando a porta 8080, e finalizar o processo
# netstat -ano | findstr :8080
# taskkill /PID <PID_encontrado> /F